import type { Metadata } from "next";
import { Press_Start_2P, Orbitron } from "next/font/google";
import "./globals.css";

export const orbitron = Orbitron({
  weight: ['400', '500', '600', '700'],
  subsets: ["latin"],
});

const pressStart2p = Press_Start_2P({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pomodoro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pressStart2p.className} antialiased dark`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
