import type { Metadata } from "next";
import "./globals.css";
import { pressStart2p } from "@/lib/fonts";


export const metadata: Metadata = {
  title: "Pomodoro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pressStart2p.className} antialiased dark`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
